version: 2

commit-message:
  prefix: "chore"
  prefix-development: "chore"
  include: "scope"
  
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
